version: 0.1 
 
phases: 
  install: 
    commands: 
      - npm install 
      - npm i -g create-react-app
  build: 
    commands: 
      - npm run build
 
artifacts: 
  files: 
    - '**/*' 
  base-directory: 'build' 
  name: my-reactdevopsapp